#!/bin/sh

#
# Copyright © 2015-present The GradleFx Project.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
# Gradle start up script for POSIX generated by Gradle.
#
# Optional ENV vars
# -----------------
#   GRADLE_OPTS - JVM options for Gradle itself
#   JAVA_OPTS - JVM options for the daemon process
#       (an additional JVM options for the main Gradle process can be added with the --gradle-user-home option)
#   JAVA_HOME - location of a JDK home dir (optional if 'java' command is in PATH)
#   GRADLE_HOME - location of gradle installation (if not set, will use the parent directory of this script)
#
#   Configuration of the native services daemon
#   GRADLE_OPTS - JVM options for the daemon process
#       (an additional JVM options for the main Gradle process can be added with the --gradle-user-home option)
#   GRADLE_DAEMON_OPTS - JVM options for the daemon process
#       (an additional JVM options for the main Gradle process can be added with the --gradle-user-home option)
#
##############################################################################

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS="-Xmx64m -Xms64m"

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD="maximum"

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
case "$(uname -s)" in                #(
  CYGWIN* )     cygwin=true  ;; #(
  Darwin* )     darwin=true  ;; #(
  MSYS* | MINGW* ) msys=true ;;
esac

# For Cygwin or MSYS, ensure paths are in Windows format before running java
if $cygwin || $msys ; then
    APP_HOME="$(cd "$(dirname "$0")" ; pwd -P)"
    APP_HOME_DIR=`dirname "$APP_HOME"`
else
    # Determine the location of the script
    SCRIPT_DIR="$(cd "$(dirname "$0")" ; pwd -P)"
    # Follow symlinks to the real script location
    while [ -h "$SCRIPT_DIR/$0" ] ; do
        ls=`ls -ld "$SCRIPT_DIR/$0"`
        link=`expr "$ls" : '.*-> \(.*\)$'`
        case "$link" in             #(
          /*)   SCRIPT_DIR="" ;;
          *)    SCRIPT_DIR="$(dirname "$SCRIPT_DIR/$0")" ;;
        esac
    done

    # Change to the directory of the script
    cd "$SCRIPT_DIR"
    # Set APP_HOME to the parent directory of the script location
    APP_HOME=`dirname "$SCRIPT_DIR"`
fi

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD="java"
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if $cygwin || $darwin || $msys ; then
    MAX_FD_LIMIT=`ulimit -H -n`
    if [ $? -eq 0 ] ; then
        if [ "$MAX_FD_LIMIT" = "unlimited" ] || [ "$MAX_FD_LIMIT" -gt "$MAX_FD" ] ; then
            [ "$MAX_FD" = "maximum" ] && MAX_FD="$MAX_FD_LIMIT"
            ulimit -n $MAX_FD
            if [ $? -ne 0 ] ; then
                warn "Could not set maximum file descriptor limit: $MAX_FD"
            fi
        else
            warn "Could not set maximum file descriptor limit: $MAX_FD"
        fi
    else
        warn "Could not query maximum file descriptor limit: $MAX_FD_LIMIT"
    fi
fi

# For Darwin, add options to make the broken security manager work.
if $darwin ; then
    export JAVA_OPTS="$JAVA_OPTS -Djava.security.manager=allow"
fi

# For Cygwin, switch the path to Windows format before running java
if $cygwin ; then
    APP_HOME=`cygpath --path --mixed "$APP_HOME"`
    CLASSPATH=`cygpath --path --mixed "$CLASSPATH"`
    JAVACMD=`cygpath --exe "$JAVACMD"`
fi

# For MSYS, switch the path to Windows format before running java
if $msys ; then
    APP_HOME=`winpty cygpath --path --mixed "$APP_HOME"`
    CLASSPATH=`winpty cygpath --path --mixed "$CLASSPATH"`
    JAVACMD=`winpty cygpath --exe "$JAVACMD"`
fi

# Build the classpath
WRAPPER_JAR="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"
CLASSPATH=$WRAPPER_JAR

# Build the JVM options
JVM_OPTS="-Dorg.gradle.appname=$APP_BASE_NAME $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS"

# Build the arguments for the JVM
eval set -- "\"$JAVACMD\"" $JVM_OPTS -classpath "\"$CLASSPATH\"" org.gradle.wrapper.GradleWrapperMain "$@"

# Execute the command
exec "$@"