name: Pull Request Check

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Set execute permissions for gradlew
      run: |
        chmod +x $GITHUB_WORKSPACE/gradlew
      shell: bash

    - name: Lint
      run: |
        $GITHUB_WORKSPACE/gradlew lint
      shell: bash

    - name: Unit Tests
      run: |
        $GITHUB_WORKSPACE/gradlew test
      shell: bash

    - name: Build Debug (Android 11+)
      run: |
        $GITHUB_WORKSPACE/gradlew assembleDebug -PminSdk=30
      shell: bash

    - uses: actions/upload-artifact@v4
      with:
        name: pr-debug-apk
        path: app/build/outputs/apk/debug/*.apk