name: Pull Request Check

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - run: chmod +x ./gradlew
      working-directory: ${{ github.workspace }}

    - name: Lint
      run: ./gradlew lint
      working-directory: ${{ github.workspace }}

    - name: Unit Tests
      run: ./gradlew test
      working-directory: ${{ github.workspace }}

    - name: Build Debug (Android 11+)
      run: ./gradlew assembleDebug -PminSdk=30
      working-directory: ${{ github.workspace }}

    - uses: actions/upload-artifact@v4
      with:
        name: pr-debug-apk
        path: app/build/outputs/apk/debug/*.apk