name: Test Commits

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to test"
        required: true
        default: "main"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch }}

    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        packages: |
          platforms;android-33
          build-tools;33.0.0
          platform-tools
        accept-android-sdk-licenses: true
      env:
        SKIP_JDK_VERSION_CHECK: true

    - run: chmod +x ./gradlew
      working-directory: .

    - name: Clean
      run: ./gradlew clean
      working-directory: .

    - name: Build Release (Android 11+)
      run: ./gradlew assembleRelease -PminSdk=30
      working-directory: .

    - name: Unit tests
      run: ./gradlew testReleaseUnitTest
      working-directory: .

    - uses: actions/upload-artifact@v4
      with:
        name: tested-release
        path: app/build/outputs/apk/release/*.apk